@API_URL = {{$dotenv API_URL}}

### POST ask - Ask a question to the IA
POST {{API_URL}}/ai/ask
Content-Type: application/json

{
  "prompt": "Hola"
}

### GET history - Get the messages history
GET {{API_URL}}/ai/messages
